(() => {
  if (window.BarStockEmailOrder?.active) return;

  let _emailOrderContext = null;
  let _emailOrderJpgBase64 = null;

  const ENDPOINT = 'https://barstock-app.vercel.app/api/send-order';

  function isValidEmail(email) {
    if (!email) return false;
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
  }

  function getContextData() {
    if (!_emailOrderContext) return null;

    if (_emailOrderContext.type === 'history') {
      const order = _emailOrderContext.order;
      return {
        vendor: order.vendor,
        items: order.items,
        totalUnits: order.totalUnits,
        subtotal: order.subtotal
      };
    }

    const vendor = _emailOrderContext.vendor;
    const items = _emailOrderContext.rows.map(r => ({
      item: r.item,
      code: r.code,
      finalOrder: typeof getEffectiveOrder === 'function' ? getEffectiveOrder(r) : r.toOrder
    }));
    const totalUnits = items.reduce((sum, r) => sum + Number(r.finalOrder || 0), 0);
    const subtotal = typeof computeOrderSubtotal === 'function'
      ? computeOrderSubtotal(_emailOrderContext.rows)
      : 0;

    return { vendor, items, totalUnits, subtotal };
  }

  async function generatePdfBase64(vendor, items, summary) {
    const { jsPDF } = window.jspdf;
    const pdf = new jsPDF({ unit: 'pt', format: 'letter' });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 40;
    let y = margin;
    const fontFamily = 'helvetica';

    // Logo (preserves aspect ratio)
    try {
      const logoUrl = 'assets/barstock_logo_full_transparent.png';
      const logoData = await fetch(logoUrl).then(r => r.blob()).then(b => new Promise(res => {
        const fr = new FileReader();
        fr.onload = () => res(fr.result);
        fr.readAsDataURL(b);
      }));
      const logoImg = new Image();
      await new Promise(res => { logoImg.onload = res; logoImg.src = logoData; });
      const logoTargetHeight = 40;
      const logoWidth = logoImg.width * (logoTargetHeight / logoImg.height);
      pdf.addImage(logoData, 'PNG', margin, y, logoWidth, logoTargetHeight);
    } catch(e) { console.warn('Logo not loaded', e); }

    // Title
    pdf.setFont(fontFamily, 'bold');
    pdf.setFontSize(20);
    pdf.setTextColor(15, 23, 42);
    pdf.text('BarStock Pro Order', pageWidth - margin, y + 18, { align: 'right' });
    y += 60;

    // Divider
    pdf.setDrawColor(226, 232, 240);
    pdf.setLineWidth(1);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 24;

    // Order Summary
    pdf.setFont(fontFamily, 'bold');
    pdf.setFontSize(14);
    pdf.text('ORDER SUMMARY', margin, y);
    y += 20;

    pdf.setFont(fontFamily, 'normal');
    pdf.setFontSize(11);
    const summaryLines = [
      ['Location:', summary.location],
      ['Vendor:', summary.vendor],
      ['Date:', summary.date],
      ['Items:', String(summary.items)],
      ['Total units:', String(summary.totalUnits)]
    ];
    summaryLines.forEach(([label, value]) => {
      pdf.setTextColor(100, 116, 139);
      pdf.text(label, margin, y);
      pdf.setTextColor(15, 23, 42);
      pdf.setFont(fontFamily, 'bold');
      pdf.text(value, margin + 90, y);
      pdf.setFont(fontFamily, 'normal');
      y += 16;
    });

    y += 20;

    // Items table header
    pdf.setFont(fontFamily, 'bold');
    pdf.setFontSize(14);
    pdf.setTextColor(15, 23, 42);
    pdf.text('ITEMS', margin, y);
    y += 12;

    const tableBody = (items || []).map(item => [
      String(item.code || ''),
      String(item.item || ''),
      String(item.finalOrder || 0)
    ]);

    pdf.autoTable({
      startY: y,
      head: [['CODE', 'ITEM', 'QTY']],
      body: tableBody,
      margin: { left: margin, right: margin },
      styles: {
        font: fontFamily,
        fontSize: 10,
        cellPadding: 6,
        textColor: [15, 23, 42],
        lineColor: [226, 232, 240],
        lineWidth: 0.5
      },
      headStyles: {
        fillColor: [241, 245, 249],
        textColor: [15, 23, 42],
        fontStyle: 'bold',
        halign: 'left'
      },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 60, halign: 'right', fontStyle: 'bold' }
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252]
      }
    });

    // Footer
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.setFont(fontFamily, 'normal');
    pdf.setFontSize(9);
    pdf.setTextColor(148, 163, 184);
    pdf.text('Generated by BarStock Pro - Automated ordering system', pageWidth / 2, pageHeight - 24, { align: 'center' });

    return pdf.output('datauristring').split(',')[1];
  }

  async function openModal(historyOrderId) {
    const modal = document.getElementById('emailOrderModalBg');
    const label = document.getElementById('emailOrderModalLabel');
    const toInput = document.getElementById('emailOrderTo');
    const ccInput = document.getElementById('emailOrderCc');
    const preview = document.getElementById('emailOrderPreview');

    if (!modal) return;

    let vendor, rows;

    if (historyOrderId) {
      const order = (state.orderHistory || []).find(o => o.id === historyOrderId);
      if (!order) return;
      _emailOrderContext = { type: 'history', order };
      vendor = order.vendor;
      rows = order.items;
      label.textContent = vendor + ' order - ' + new Date(order.createdAt).toLocaleDateString();
    } else {
      vendor = typeof activeVendorTab !== 'undefined' ? activeVendorTab : 'ALL';
      rows = (typeof getOrderRowsForVendor === 'function' ? getOrderRowsForVendor(vendor) : [])
        .filter(r => Number((typeof parseNum === 'function' ? parseNum(r.finalOrder) : r.finalOrder) || 0) > 0);
      if (!rows.length) {
        alert('No items to email for this vendor.');
        return;
      }
      _emailOrderContext = { type: 'current', vendor, rows };
      label.textContent = vendor + ' order - ' + rows.length + ' items';
    }

    if (toInput) toInput.value = '';
    if (ccInput) ccInput.value = '';
    if (preview) preview.innerHTML = '<div class="small muted">Generating preview...</div>';
    _emailOrderJpgBase64 = null;
    modal.classList.remove('hidden');

    try {
      const canvas = await generateVendorJpgCanvas(vendor, rows);
      const dataUrl = canvas.toDataURL('image/jpeg', 0.95);
      _emailOrderJpgBase64 = dataUrl.split(',')[1];
      if (preview) {
        preview.innerHTML = '<img src="' + dataUrl + '" style="max-width:100%;height:auto;border-radius:6px;display:block">';
      }
    } catch (err) {
      console.error('Preview generation failed:', err);
      if (preview) {
        preview.innerHTML = '<div class="small" style="color:#ef4444">Could not generate preview: ' + err.message + '</div>';
      }
    }
  }

  function closeModal() {
    document.getElementById('emailOrderModalBg')?.classList.add('hidden');
    _emailOrderContext = null;
    _emailOrderJpgBase64 = null;
  }

  async function send() {
    const to = String(document.getElementById('emailOrderTo')?.value || '').trim();
    const cc = String(document.getElementById('emailOrderCc')?.value || '').trim();
    const btn = document.getElementById('emailOrderSendBtn');

    if (!isValidEmail(to)) {
      alert('Please enter a valid recipient email.');
      return;
    }

    if (cc && !isValidEmail(cc)) {
      alert('CC field is not a valid email. Leave it empty or enter a valid email.');
      return;
    }

    if (!_emailOrderContext) return;
    if (!_emailOrderJpgBase64) {
      alert('Preview not ready yet, please wait.');
      return;
    }

    const data = getContextData();
    if (!data) return;

    const locationName = (window.BARSTOCK_CONFIG || {}).LOCATION_NAME || 'BarStock';
    const dateStr = new Date().toISOString().slice(0, 10);
    const filename = data.vendor.toLowerCase().replace(/\s+/g, '_') + '_order_' + dateStr + '.pdf';

    if (typeof setButtonBusy === 'function') setButtonBusy(btn, 'SENDING');

    try {
      // Generate PDF with summary + items table
      const pdfBase64 = await generatePdfBase64(data.vendor, data.items, {
        location: locationName,
        vendor: data.vendor,
        date: new Date().toLocaleDateString(),
        items: data.items.length,
        totalUnits: data.totalUnits
      });

      const payload = {
        to,
        vendor: data.vendor,
        items: data.items,
        totalUnits: data.totalUnits,
        subtotal: data.subtotal,
        locationName,
        jpgBase64: _emailOrderJpgBase64,
        pdfBase64,
        filename
      };

      if (cc) payload.cc = cc;

      const res = await fetch(ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      const result = await res.json();
      if (!result.ok) throw new Error(result.error || 'Unknown error');

      closeModal();
      if (typeof setStatus === 'function') setStatus('Order emailed to ' + to + '.');

      if (window.BarStockLogger) {
        window.BarStockLogger.log('email_order_sent', {
          vendor: data.vendor,
          to,
          cc: cc || null,
          itemCount: data.items.length
        });
      }
    } catch (err) {
      console.error(err);
      alert('Could not send email: ' + err.message);
    } finally {
      if (typeof clearButtonBusy === 'function') clearButtonBusy(btn);
    }
  }

  function bindModalBackdrop() {
    const bg = document.getElementById('emailOrderModalBg');
    if (!bg) return;
    bg.addEventListener('click', function(e) {
      if (e.target.id === 'emailOrderModalBg') closeModal();
    });
  }

  window.openEmailOrderModal = openModal;
  window.closeEmailOrderModal = closeModal;
  window.sendEmailOrder = send;

  window.BarStockEmailOrder = {
    active: true,
    openModal,
    closeModal,
    send,
    isValidEmail
  };

  document.addEventListener('DOMContentLoaded', bindModalBackdrop);
})();
